name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: List Files (Debugging)
        run: ls -R  # Shows all files in the runner to debug missing files

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3  # Use v3 instead of v4
        with:
          path: './'  # Change if files are inside a subfolder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
